#!/bin/bash

# Based on https://github.com/vilmibm/gh-user-status/blob/533285348c0354064d79053da39aa75f17b5c55f/gh-user-status

set -e

extensionPath="$(dirname "$0")"

# Get the most recent tag, or a commit if no tags availble e.g. within a shallow clone.
repo=heaths/gh-label
tag="$(git --git-dir="${extensionPath}/.git" describe --abbrev=0 --always --tags)"

arch="$(uname -m)"
exec=""

if uname -a | grep Msys > /dev/null; then
  if [ $arch = "x86_64" ]; then
    exe="windows-x86_64"
  elif [ $arch = "i686" ]; then
    exe="windows-i386"
  elif [ $arch = "i386" ]; then
    exe="windows-i386"
  fi
elif uname -a | grep Darwin > /dev/null; then
  if [ $arch = "x86_64" ]; then
    exe="darwin-x86_64"
  fi
elif uname -a | grep Linux > /dev/null; then
  if [ $arch = "x86_64" ]; then
    exe="linux-x86_64"
  elif [ $arch = "i686" ]; then
    exe="linux-i386"
  elif [ $arch = "i386" ]; then
    exe="linux-i386"
  fi
fi

if [ "${exe}" == "" ]; then
  if [ "$(which go)" == "" ]; then
    echo "Go must be installed to use this gh extension on this platform: https://golang.org"
    exit 1
  fi

  pushd "${extensionPath}" > /dev/null
  go run . "$@"
  popd > /dev/null

  exit
fi

if [[ ! -x "${extensionPath}/bin/${tag}/${exe}" ]]; then
  rm -rf "${extensionPath}"/bin/*

  if [[ $tag =~ ^v[0-9\.]+ ]]; then
    >&2 echo "Downloading ${exe} from https://github.com/${repo}/releases/tag/${tag}"
    gh release -R "${repo}" download "${tag}" -p "${exe}" --dir="${extensionPath}/bin/${tag}"
  else
    # Fall back to latest executable since no tag was available.
    >&2 echo "Downloading latest executable from https://github.com/${repo}/releases/latest"
    gh release -R "${repo}" download -p "${exe}" --dir="${extensionPath}/bin/${tag}"
  fi

  chmod +x "${extensionPath}/bin/${tag}/${exe}"
fi

exec "${extensionPath}/bin/${tag}/${exe}" "$@"
