name: release

on:
  release:
    types:
    - published

defaults:
  run:
    shell: bash

env:
  GOVERSION: 1.17

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install go ${{ env.GOVERSION }}
      uses: actions/setup-go@v2.1.4
      with:
        go-version: '^${{ env.GOVERSION }}'
    - name: test
      run: go test ./...
    - name: build
      run: |
        mkdir -p bin
        GOOS=darwin  GOARCH=amd64 go build -o bin/darwin-x86_64
        GOOS=linux   GOARCH=386   go build -o bin/linux-i386
        GOOS=linux   GOARCH=amd64 go build -o bin/linux-x86_64
        GOOS=windows GOARCH=386   go build -o bin/windows-i386
        GOOS=windows GOARCH=amd64 go build -o bin/windows-x86_64

    - name: publish
      run: gh release upload ${GITHUB_REF#refs/tags/} ./bin/* --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
