name: release

on:
  release:
    types:
    - published

defaults:
  run:
    shell: bash

env:
  # TODO: Update once cli/gh-extension-precompile#5 is resolved.
  GOVERSION: 1.16

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install go ${{ env.GOVERSION }}
      uses: actions/setup-go@v2.1.4
      with:
        go-version: '^${{ env.GOVERSION }}'
    - name: test
      run: go test ./...
    - name: publish
      uses: cli/gh-extension-precompile@v1
